lgpage/rxtutor

CONTRIBUTING.md
README.md

Update README and add CONTRIBUTING

---

src/app/app.module.ts

fix: provide log level as warning for production

---

.github/workflows/azure-static-web-apps.yml
.github/workflows/lint-test-build-pull-request.yml
README.md
codecov.yml
karma.conf.js

chore: add codecov and update readme

---

src/app/examples.ts
src/app/examples/combine-latests.spec.ts
src/app/examples/debounce-time.spec.ts
src/app/examples/debounce-time.ts
src/app/examples/merge-map.spec.ts
src/app/services/stream.builder.ts

feat: add debounceTime example

---

codecov.yml

chore: fix codecov config file

---

renovate.json

Closes #171 (Will require disabling dependabot once all set up, though)
@lgpage, will need you to install app [here](https://github.com/apps/renovate), welcome to install for all your repos if you like. Can check out installation docs [here](https://docs.renovatebot.com/getting-started/installing-onboarding/#hosted-githubcom-app).
The config in this PR is the config I've been using, welcome to suggest changes for labels and timing. Can see available config [here](https://docs.renovatebot.com/configuration-options/#)

chore(tools): add renovate[bot] config

---

renovate.json

chore(tools): set renovate dashboard title

---

src/app/examples.ts
src/app/examples/combine-latests.spec.ts
src/app/examples/concat.spec.ts
src/app/examples/concat.ts
src/app/examples/merge-map.spec.ts
src/index.html

feat: add concat example

---

src/app/examples.ts
src/app/examples/throttle-time.spec.ts
src/app/examples/throttle-time.ts

feat: add throttleTime example

---

src/app/examples.ts
src/app/examples/start-with.spec.ts
src/app/examples/start-with.ts

feat: add startWith example

---

src/app/examples.ts
src/app/examples/with-latest-from.spec.ts
src/app/examples/with-latest-from.ts

feat: add withLatestFrom example

---

src/app/examples.ts
src/app/examples/merge.spec.ts
src/app/examples/merge.ts

feat: add merge example

---

.eslintrc.json
src/app/app.component.ts
src/app/components/sandbox-controller/sandbox-controller.component.ts
src/app/core/helpers/form.ts
src/app/core/helpers/marble.spec.ts
src/app/core/helpers/marble.ts
src/app/core/helpers/notification.ts
src/app/core/helpers/numerical.ts
src/app/core/helpers/stream.ts
src/app/core/stream-observable.ts
src/app/core/visualization.scheduler.ts
src/app/examples/combine-latest.ts
src/app/examples/combine-latests.spec.ts
src/app/examples/concat.spec.ts
src/app/examples/concat.ts
src/app/examples/debounce-time.spec.ts
src/app/examples/debounce-time.ts
src/app/examples/merge-map.spec.ts
src/app/examples/merge-map.ts
src/app/examples/sandbox.ts
src/app/examples/throttle-time.spec.ts
src/app/examples/throttle-time.ts
src/app/services/executor.service.ts
src/app/services/stream.builder.spec.ts

chore: tweak eslint rules and fix lint issues

---

src/app/app.module.ts
src/app/components/side-nav/side-nav.component.html
src/app/components/side-nav/side-nav.component.spec.ts
src/styles/main.scss

feat: improve side nav styling

---

.eslintrc.json
src/app/components/stream-options/stream-options.component.ts
src/app/core/helpers/stream.ts
src/app/core/visualization.scheduler.ts
src/app/examples.ts
src/app/examples/combine-latests.spec.ts
src/app/examples/concat.spec.ts
src/app/examples/merge-map.spec.ts
src/app/examples/merge.spec.ts
src/app/examples/of.spec.ts
src/app/examples/of.ts
src/app/examples/start-with.spec.ts
src/app/examples/with-latest-from.spec.ts
src/app/services/executor.service.ts
src/app/services/logger.service.ts

feat: add of example

---

src/app/components/side-nav/side-nav.component.ts
src/app/core/types/example.ts
src/app/examples.ts
src/app/examples/catch-error.spec.ts
src/app/examples/catch-error.ts

feat: add catchError example

---

src/app/examples.ts
src/app/examples/from.spec.ts
src/app/examples/from.ts

feat: add from example

---

src/app/examples.ts
src/app/examples/filter.spec.ts
src/app/examples/filter.ts

feat: add filter example

---

src/app/examples.ts
src/app/examples/take.spec.ts
src/app/examples/take.ts

feat: add take example

---

src/app/examples.ts
src/app/examples/distinct-until-changed.spec.ts
src/app/examples/distinct-until-changed.ts

feat: add distinctUntilChanged example

---

src/app/examples.ts
src/app/examples/tap.spec.ts
src/app/examples/tap.ts

feat: add tap example

---

src/app/examples.ts
src/app/examples/delay.spec.ts
src/app/examples/delay.ts

feat: add delay example

---

src/app/examples.ts
src/app/examples/finalize.spec.ts
src/app/examples/finalize.ts

feat: add finalize example

---

src/app/examples.ts
src/app/examples/map.spec.ts
src/app/examples/map.ts

feat: add map example

---

src/app/examples.ts
src/app/examples/concat-map.spec.ts
src/app/examples/concat-map.ts

feat: add concatMap example

---

src/app/examples.ts
src/app/examples/switch-map.spec.ts
src/app/examples/switch-map.ts

feat: add switchMap example

---

src/app/examples.ts
src/app/examples/scan.spec.ts
src/app/examples/scan.ts

feat: add scan example

---

src/app/examples.ts
src/app/examples/buffer-time.spec.ts
src/app/examples/buffer-time.ts

feat: add bufferTime example

---

src/app/components/stream-controller/stream-controller.component.html
src/app/components/stream-controller/stream-controller.component.ts

fix: stream marbles tooltip not showing

---

src/app/examples/combine-latests.spec.ts
src/app/examples/concat.spec.ts
src/app/examples/distinct-until-changed.spec.ts
src/app/examples/filter.spec.ts
src/app/examples/finalize.spec.ts
src/app/examples/merge-map.spec.ts
src/app/examples/merge.spec.ts
src/app/examples/take.spec.ts

chore: update example specs
